### ISSUE TITLE
GESIS package

### ISSUE THREAD

**Issue by dongericoyu** [fsolt/DCPO#12]
Hi Fred,

So I set up the codes for download ISSP dataset from gesis, but the r code returns me with error as below:

"Error in file(tmpfile, "rb") : cannot open the connection
In addition: Warning messages:
1: running command '"zip" -r9Xjq "C:\Users\Dong\AppData\Local\Temp\Rtmp21sDtJ\file1cfc6e4a4cdf.zip" "C:\Users\Dong\AppData\Local\Temp\Rtmp21sDtJ/firefoxprofile/prefs.js" ' had status 127 
2: In file(tmpfile, "rb") :
  cannot open file 'C:\Users\Dong\AppData\Local\Temp\Rtmp21sDtJ\file1cfc6e4a4cdf.zip': No such file or directory"

Do you know what's going on here?

**Comment by fsolt** [comment]
Okay, let's try this instead:

```
devtools::install_github("fsolt/gesis")
library(gesis)

# Fill in your info below
options("gesis_user" = "juanita-herrera@uppermidwest.edu",
        "gesis_pass" = "password123!")

gesis_download(c(1490, 1620, 1680)) # and so on; these are the three oldest studies
# DOI for this purpose is the ZA code number, not the real doi:whatever.numbers link
```

**Comment by dongericoyu** [comment]
I tried your codes after reinstalled rtools and set up my system variables. 

Then a new issue comes up:
Error: 	 Summary: UnknownError
 	 Detail: An unknown server-side error occurred while processing the command.
 	 class: java.net.SocketException

I tried three different gesis packages (yours, GESIS, and expresso/gesis), and all return me with this error.
I'm not sure it is a problem exists in the package of RSelenium (as many posts on stackoverflow indicates) when it tries to open a browser (in my case, R tries to launch Firefox and shut down with errors) to connect the server.  

Do you have any problem when you run the code on your mac?

**Comment by fsolt** [comment]
Nope, works perfectly here.  I think Hu mentioned having Windows problems with these packages as well.  Oh well.  In the meantime, I guess you're back to clicking through the website.  Maybe you all should consider Ubuntu if you don't want to pony up for a Mac . . . ;)

**Comment by dongericoyu** [comment]
Yep, I guess this is way to get the data right now without messing my laptop before the comp. 

Will keep you posted if I encounter further issues. Thanks!
