### ISSUE TITLE
Fail to install DCPO.

### ISSUE THREAD

**Issue by Tyhcass** [fsolt/DCPO#32]
@fsolt, On macOS Catalina, in order to install_github("fsolt/DCPOtools") and install_github("fsolt/DCPO") successfully, install_github("expersso/gesis") and install_github("fsolt/gesisdata") are needed. 

However, on Windows10,  DCPOtools can be installed by manually installing DCPOtools_0.1.0.9000.tar.gz. However, I failed to install DCPO. Even I tried to manually install DCPO_0.5.3.tar.gz, it always shows `DCPO_0.5.3.tar.gz’ had non-zero exit status. Also, if I chose to update All, the Error message is : Failed to install 'DCPO' from GitHub:
  (converted from warning) installation of package ‘vctrs’ had non-zero exit status. However vctrs is installed and used by DCPOtools.

**Comment by fsolt** [comment]
DCPO is on CRAN (at the moment, at least), so
 
`install.packages(“DCPO”)`
 
should work just fine

**Comment by fsolt** [comment]
(I also deleted `DCPOtool`'s dependency on `expersso/gesis`.  Thanks for pointing that out.)

**Comment by Tyhcass** [comment]
@fsolt  I tried to download DCPO in CRAN first and failed,  then I used remote install. The error message is "ERROR: compilation failed for package 'DCPO'
* removing 'C:/Users/skywa/OneDrive/Documents/R/win-library/3.6/DCPO'
Warning in install.packages :
  installation of package ‘DCPO’ had non-zero exit status.    I think it is a similar problem with installing via remote. 
Then, when I used library(DCPO), it shows no package called ‘DCPO’.

**Comment by fsolt** [comment]
Blech.  Same story on your MBP?

**Comment by fsolt** [comment]
Yeah, I see the Windows builds errored out on CRAN this time <https://cran.r-project.org/web/checks/check_results_DCPO.html>.  Weirdly, they haven't always, though the only changes across versions have been in the examples.

**Comment by Tyhcass** [comment]
No errors on Mac at all.  Windows versions.... @sammo3182, check here.  Version problem!

**Comment by fsolt** [comment]
Hmm--today I see the latest r-devel passes on Windows . . .

**Comment by fsolt** [comment]
again here that is: https://cran.r-project.org/web/checks/check_results_DCPO.html

**Comment by fsolt** [comment]
Okay to close this now?

**Comment by Tyhcass** [comment]
Yes, please.  The installation problem is solved.
